spring:
  application:
    name: flashsale-service

  datasource:
    url: jdbc:mysql://220.117.238.181:3306/flash_sale?serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: admin
    password: admin123
    hikari:
      maximum-pool-size: 145

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

logging:
  file:
    name: logs/flashsale-app.log  # 로그 파일 경로
  level:
    root: INFO
    com.example.flashsale_service: DEBUG  # 도메인 패키지 기준으로 설정
    com.zaxxer.hikari: DEBUG  # HikariCP 상태 확인
  pattern:
    file: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n"
